import { TaskProvider } from "@component/context/TasksContext";
import "./globals.css";
import Navbar from "@component/components/Navbar";
import { Toaster } from "./Toaster";
import { Layout } from "@component/components/Layout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <Navbar />
          <Layout>{children}</Layout>
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}
